CREATE TABLE `User` (
    `USER_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `USER_USERNAME` VARCHAR(50) NOT NULL UNIQUE,
    `USER_EMAIL` VARCHAR(100) NOT NULL UNIQUE,
    `USER_PASSWORD` VARCHAR(255) NOT NULL,
    `USER_PHONE` VARCHAR(15),
    `USER_ROLE` ENUM('Admin', 'Staff', 'Customer') NOT NULL DEFAULT 'Staff',
    `USER_STATUS` ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    `USER_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `Customer` (
    `CUSTOMER_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `CUSTOMER_FULLNAME` VARCHAR(100) NOT NULL,
    `CUSTOMER_PHONE` VARCHAR(15) NOT NULL UNIQUE,
    `CUSTOMER_EMAIL` VARCHAR(100),
    `CUSTOMER_CCCD` VARCHAR(12) DEFAULT NULL,
    `CUSTOMER_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RoomType` (
    `ROOMTYPE_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ROOMTYPE_NAME` VARCHAR(100) NOT NULL,
    `ROOMTYPE_PRICE_PER_NIGHT` DECIMAL(10,2) NOT NULL,
    `ROOMTYPE_DISCOUNT_PERCENTAGE` INT DEFAULT 0,
    `ROOMTYPE_DESCRIPTION` TEXT,
    `ROOMTYPE_THUMBNAIL` VARCHAR(255),
    `ROOMTYPE_MAX_GUESTS` INT NOT NULL DEFAULT 2,
    `ROOMTYPE_BED_TYPE` ENUM( 'singleBed', 'doubleBed', 'queenBed', 'kingBed' ) NOT NULL DEFAULT 'singleBed',
    `ROOMTYPE_STATUS` ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    `ROOMTYPE_SLUG` VARCHAR(255) NOT NULL UNIQUE,
    `ROOMTYPE_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `Room` (
    `ROOM_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ROOM_NUMBER` VARCHAR(20) NOT NULL UNIQUE,
    `ROOM_ROOMTYPE_ID` INT NOT NULL,
    `ROOM_DESCRIPTION` TEXT,
    `ROOM_STATUS` ENUM(
        'Available',
        'Booked',
        'Occupied',
        'Maintenance'
    ) DEFAULT 'Available',
    `ROOM_SLUG` VARCHAR(255) NOT NULL UNIQUE,
    `ROOM_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `FK_ROOM_ROOMTYPE`
        FOREIGN KEY (`ROOM_ROOMTYPE_ID`)
        REFERENCES `RoomType`(`ROOMTYPE_ID`)
);

CREATE TABLE `Booking` (
    `BOOKING_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `BOOKING_CUSTOMER_ID` INT NOT NULL,
    `BOOKING_ROOMTYPE_ID` INT NOT NULL,
    `BOOKING_ROOM_ID` INT DEFAULT NULL,
    `BOOKING_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `BOOKING_CHECKIN` DATE NOT NULL,
    `BOOKING_CHECKOUT` DATE NOT NULL,
    `BOOKING_TOTAL_PRICE` DECIMAL(10,2),
    `BOOKING_STATUS`
        ENUM(
            'Pending',
            'Confirmed',
            'CheckedIn',
            'CheckedOut',
            'Cancelled'
        ) DEFAULT 'Pending',

    `BOOKING_NOTE` TEXT,

    `BOOKING_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT `FK_BOOKING_CUSTOMER`
        FOREIGN KEY (`BOOKING_CUSTOMER_ID`)
        REFERENCES `Customer`(`CUSTOMER_ID`),

    CONSTRAINT `FK_BOOKING_ROOMTYPE`
        FOREIGN KEY (`BOOKING_ROOMTYPE_ID`)
        REFERENCES `RoomType`(`ROOMTYPE_ID`),

    CONSTRAINT `FK_BOOKING_ROOM`
        FOREIGN KEY (`BOOKING_ROOM_ID`)
        REFERENCES `Room`(`ROOM_ID`)
);
