CREATE TABLE `Account` (
    `ACCOUNT_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ACCOUNT_FULLNAME` VARCHAR(100) NOT NULL,
    `ACCOUNT_USERNAME` VARCHAR(50) NOT NULL UNIQUE,
    `ACCOUNT_EMAIL` VARCHAR(100) NOT NULL UNIQUE,
    `ACCOUNT_PASSWORD` VARCHAR(255) NOT NULL,
    `ACCOUNT_PHONE` VARCHAR(15),
    `ACCOUNT_AVATAR` VARCHAR(255),
    `ACCOUNT_ROLE` ENUM('Admin','User') NOT NULL DEFAULT 'User',
    `ACCOUNT_STATUS` ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    `ACCOUNT_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `ACCOUNT_DELETED_AT` DATETIME DEFAULT NULL
);

CREATE TABLE `Amenity` (
    `AMENITY_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `AMENITY_NAME` VARCHAR(100) NOT NULL,
    `AMENITY_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `AMENITY_DELETED_AT` DATETIME DEFAULT NULL
);

CREATE TABLE `RoomType` (
    `ROOMTYPE_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ROOMTYPE_NAME` VARCHAR(100) NOT NULL,
    `ROOMTYPE_PRICE_PER_NIGHT` DECIMAL(10,2) NOT NULL,
    `ROOMTYPE_DISCOUNT_PERCENTAGE` INT DEFAULT 0,
    `ROOMTYPE_DESCRIPTION` TEXT,
    `ROOMTYPE_THUMBNAIL` VARCHAR(255),
    `ROOMTYPE_SLUG` VARCHAR(255) NOT NULL UNIQUE,
    `ROOMTYPE_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `ROOMTYPE_DELETED_AT` DATETIME DEFAULT NULL
);

CREATE TABLE `Room` (
    `ROOM_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `ROOM_NUMBER` VARCHAR(20) NOT NULL UNIQUE,
    `ROOM_ROOMTYPE_ID` INT NOT NULL,
    `ROOM_DESCRIPTION` TEXT,
    `ROOM_STATUS` ENUM(
        'Available',
        'Booked',
        'Occupied',
        'Maintenance'
    ) DEFAULT 'Available',
    `ROOM_CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `ROOM_DELETED_AT` DATETIME DEFAULT NULL,

    CONSTRAINT `FK_ROOM_ROOMTYPE`
        FOREIGN KEY (`ROOM_ROOMTYPE_ID`)
        REFERENCES `RoomType`(`ROOMTYPE_ID`)
);

CREATE TABLE `RoomTypeAmenities` (
    `RTA_ROOM_TYPE_ID` INT NOT NULL,
    `RTA_AMENITY_ID` INT NOT NULL,

    PRIMARY KEY (`RTA_ROOM_TYPE_ID`, `RTA_AMENITY_ID`),

    CONSTRAINT `FK_RTA_ROOMTYPE`
        FOREIGN KEY (`RTA_ROOM_TYPE_ID`)
        REFERENCES `RoomType`(`ROOMTYPE_ID`)
        ON DELETE CASCADE,

    CONSTRAINT `FK_RTA_AMENITY`
        FOREIGN KEY (`RTA_AMENITY_ID`)
        REFERENCES `Amenity`(`AMENITY_ID`)
        ON DELETE CASCADE
);